function move = not2vec(move)
    pieceStruct = struct('N', PieceClass.Knight,...
                         'B', PieceClass.Bishop,...
                         'R', PieceClass.Rook,  ...
                         'Q', PieceClass.Queen, ...
                         'K', PieceClass.King);
    characters = num2cell(move);
end