function moveList = kingGen(game, origin)
moveList = [origin origin+[0 -1];...
    origin origin+[0 1];...
    origin origin+[-1 0];...
    origin origin+[1 0];...
    origin origin+[-1 -1];...
    origin origin+[-1 1];...
    origin origin+[1 1];...
    origin origin+[1 -1]];

for move = 8:-1:1
    flag = false;
    for coordinate = 3:4
        if ~flag && moveList(move,coordinate) < 1 || moveList(move,coordinate) > 8
            moveList(move,:) = [];
            flag = true;
            break
        end
    end
    if ~flag ...
            && game.pBit(moveList(move, 3), moveList(move, 4))...
            && game.Turn == getColour(game.Board(moveList(move, 3), moveList(move, 4)))
        moveList(move,:) = [];
    end
end